package com.superhumans.prosthesismanufacturing.controller;

import com.superhumans.exception.NotFoundException;
import com.superhumans.mis.MisService;
import com.superhumans.mis.dto.DocumentMisDTO;
import com.superhumans.prosthesismanufacturing.dto.OrderDocumentResponse;
import com.superhumans.prosthesismanufacturing.entity.ProstheticsOrder;
import com.superhumans.prosthesismanufacturing.repository.ProstheticsOrderRepository;
import com.superhumans.prosthesismanufacturing.service.ProstheticsOrderService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;
import lombok.experimental.FieldDefaults;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/prosthesis-manufacturing/orders")
@RequiredArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
@Validated
@Tag(name = "Prosthetics orders", description = "Read-only order registry (Doctor Eleks)")
public class ProstheticsOrderController {

    ProstheticsOrderService orderService;
    ProstheticsOrderRepository orderRepository;
    MisService misService;

    @GetMapping
    @PreAuthorize("@permissionService.hasAny('PROSTHETICS_DASHBOARD','MODULE_PROSTHETICS_ACCESS')")
    @Operation(summary = "List orders")
    public List<com.superhumans.prosthesismanufacturing.dto.ProstheticsOrderResponse> list(
            @org.springframework.web.bind.annotation.RequestParam(required = false)
            @jakarta.validation.constraints.Pattern(regexp = "\\d+",
                    message = "ID пацієнта має містити лише цифри") String patientId,
            @org.springframework.web.bind.annotation.RequestParam(required = false) String status) {
        return orderService.list(patientId, status);
    }

    @GetMapping("/{id}")
    @PreAuthorize("@permissionService.hasAny('PROSTHETICS_DASHBOARD','MODULE_PROSTHETICS_ACCESS')")
    @Operation(summary = "Get order by id")
    public com.superhumans.prosthesismanufacturing.dto.ProstheticsOrderResponse get(@PathVariable UUID id) {
        return orderService.get(id);
    }

    /**
     * Lists the limb-prosthesis order documents MIS holds for the patient
     * (setup step 2 — order selection). Backed by
     * {@code spiDocumentProsthesCheck} with {@code PatientID}, narrowed to
     * templates 120/121; documents whose {@code documentUrl} answers HTTP
     * 404 are excluded. The returned {@code documentUrl} values feed step 3
     * (review), which embeds them directly — no PDF is proxied or generated
     * by the application (MIS Data Policy: read-only).
     */
    @GetMapping("/documents")
    @PreAuthorize("@permissionService.hasAny('PROSTHETICS_DASHBOARD','MODULE_PROSTHETICS_ACCESS')")
    @Operation(summary = "List MIS limb-prosthesis order documents for a patient")
    public List<DocumentMisDTO> documents(
            @org.springframework.web.bind.annotation.RequestParam
            @jakarta.validation.constraints.Pattern(regexp = "\\d+",
                    message = "ID пацієнта має містити лише цифри") String patientId) {
        return orderService.getAllLowerLimbsOrdersForByPatientId(patientId);
    }

    /**
     * Returns the MIS-hosted URL for the order document
     * ({@code spiDocumentProsthesCheck} → {@code documentUrl}). The client
     * opens this URL directly — no PDF is proxied or generated by the
     * application (MIS Data Policy: read-only).
     */
    @GetMapping("/{id}/document-url")
    @PreAuthorize("@permissionService.hasAny('PROSTHETICS_DASHBOARD','MODULE_PROSTHETICS_ACCESS')")
    @Operation(summary = "Resolve MIS-hosted order document URL")
    public OrderDocumentResponse getDocumentUrl(@PathVariable UUID id) {
        ProstheticsOrder order = orderRepository.findById(id)
                .orElseThrow(() -> new NotFoundException("Order not found: " + id));
        String patientId = order.getPatient() == null ? null : order.getPatient().getId();
        if (patientId == null) {
            throw new NotFoundException("Order has no patient: " + id);
        }
        Long numericPatientId = parseLong(patientId);
        List<DocumentMisDTO> documents = misService.getPatientDocuments(numericPatientId);
        DocumentMisDTO match = documents.stream()
                .filter(d -> d.getDocumentUrl() != null && !d.getDocumentUrl().isBlank())
                .findFirst()
                .orElseThrow(() -> new NotFoundException(
                        "Замовлення на протез не знайдено в MIS для пацієнта " + patientId));
        return OrderDocumentResponse.builder()
                .documentId(match.getDocumentId())
                .documentTemplateName(match.getDocumentTemplateName())
                .documentUrl(match.getDocumentUrl())
                .build();
    }

    private static Long parseLong(String value) {
        try {
            return Long.valueOf(value);
        } catch (NumberFormatException ex) {
            throw new NotFoundException("Patient id is not numeric: " + value);
        }
    }
}
