import client from './client';
import type {
  MisOrderDocument,
  ProstheticsCandidate,
  ProstheticsPatient,
  ProstheticsOrder,
  FlowTemplate,
  FlowInstance,
  InstanceCreateRequest,
  StepCompleteRequest,
  PauseRequest,
  FailRequest,
  EvidenceFile,
  FlowInstanceStatus,
  StepExecution,
  TemplateStatus,
  TemplateCreateRequest,
  TemplatePatchRequest,
  SnapshotTemplate,
  ResourceUsageResponse,
  FailureSnapshot,
  BrakCreateRequest,
  BrakEvent,
  BranchResponse,
  StepNotePatchRequest,
  ProductionDetail,
  ProductionListParams,
  ProductionPage,
  ProductionSummary,
  ProductionWorkItem,
} from '../prosthetics/types';

const BASE = '/prosthesis-manufacturing';

export const prostheticsPatientApi = {
  search: (query?: string, signal?: AbortSignal) =>
    client.get<ProstheticsPatient[]>(`${BASE}/patients`, { params: { query }, signal }),
  getById: (id: string) => client.get<ProstheticsPatient>(`${BASE}/patients/${id}`),
  /** Eligibility worklist (Phase 9, #262): backend-filtered candidates. */
  listCandidates: (query?: string, signal?: AbortSignal) =>
    client.get<ProstheticsCandidate[]>(`${BASE}/patients/candidates`, { params: { query }, signal }),
};

export const prostheticsOrderApi = {
  list: () => client.get<ProstheticsOrder[]>(`${BASE}/orders`),
  listByPatient: (patientId: string) => client.get<ProstheticsOrder[]>(`${BASE}/orders`, { params: { patientId } }),
  /**
   * MIS limb-prosthesis order documents for setup step 2
   * (spiDocumentProsthesCheck narrowed to templates 120/121, 404 URLs excluded).
   * The picked documentUrl feeds step 3 (review).
   */
  listMisDocuments: (patientId: string, signal?: AbortSignal) =>
    client.get<MisOrderDocument[]>(`${BASE}/orders/documents`, { params: { patientId }, signal }),
  /**
   * Provisions (find-or-create) the local order for an MIS document:
   * selection never depends on pre-existing local rows.
   */
  provisionFromMis: (body: { patientId: string; documentId: number }) =>
    client.post<ProstheticsOrder>(`${BASE}/orders/provision`, body),
  getById: (id: string) => client.get<ProstheticsOrder>(`${BASE}/orders/${id}`),
  /**
   * Resolves the MIS-hosted URL for the order document. The client opens
   * {@code documentUrl} directly — no PDF is proxied or generated by the
   * backend (MIS Data Policy: read-only).
   */
  getDocumentUrl: (id: string) =>
    client.get<{ documentId?: number; documentTemplateName?: string; documentUrl: string }>(
      `${BASE}/orders/${id}/document-url`,
    ),
};

export const flowTemplateApi = {
  list: (params?: { status?: TemplateStatus; productType?: string; amputationLevel?: string; limbSide?: string }) =>
    client.get<FlowTemplate[]>(`${BASE}/templates`, { params }),
  getById: (id: string) => client.get<FlowTemplate>(`${BASE}/templates/${id}`),
  create: (data: TemplateCreateRequest) =>
    client.post<FlowTemplate>(`${BASE}/templates`, data),
  update: (id: string, data: TemplatePatchRequest) =>
    client.patch<FlowTemplate>(`${BASE}/templates/${id}`, data),
  delete: (id: string) => client.delete(`${BASE}/templates/${id}`),
};

export const flowInstanceApi = {
  list: (params?: { assignee?: number; status?: FlowInstanceStatus }) =>
    client.get<FlowInstance[]>(`${BASE}/instances`, { params }),
  getById: (id: string) => client.get<FlowInstance>(`${BASE}/instances/${id}`),
  getSnapshot: (id: string) =>
    client.get<SnapshotTemplate>(`${BASE}/instances/${id}/snapshot`),
  create: (data: InstanceCreateRequest) =>
    client.post<FlowInstance>(`${BASE}/instances`, data),
  start: (id: string) => client.post<FlowInstance>(`${BASE}/instances/${id}/start`),
  completeStep: (id: string, executionId: string, data: StepCompleteRequest) =>
    client.post<FlowInstance>(`${BASE}/instances/${id}/steps/${executionId}/complete`, data),
  backward: (id: string) => client.post<FlowInstance>(`${BASE}/instances/${id}/backward`),
  listExecutions: (id: string) =>
    client.get<StepExecution[]>(`${BASE}/instances/${id}/step-executions`),
  listResources: (id: string) =>
    client.get<ResourceUsageResponse[]>(`${BASE}/instances/${id}/resources`),
  getFailureSnapshot: (id: string) =>
    client.get<FailureSnapshot>(`${BASE}/instances/${id}/failure-snapshot`),
  pause: (id: string, data: PauseRequest) =>
    client.post<FlowInstance>(`${BASE}/instances/${id}/pause`, data),
  resume: (id: string) => client.post<FlowInstance>(`${BASE}/instances/${id}/resume`),
  fail: (id: string, data: FailRequest) =>
    client.post<FlowInstance>(`${BASE}/instances/${id}/fail`, data),
  uploadEvidence: (id: string, executionId: string, file: File) => {
    const formData = new FormData();
    formData.append('file', file);
    return client.post<EvidenceFile>(
      `${BASE}/instances/${id}/evidence?executionId=${executionId}`,
      formData,
      { headers: { 'Content-Type': 'multipart/form-data' } }
    );
  },
  listEvidence: (id: string, executionId: string) =>
    client.get<EvidenceFile[]>(`${BASE}/instances/${id}/evidence`, { params: { executionId } }),
  deleteEvidence: (id: string, fileId: string) =>
    client.delete<void>(`${BASE}/instances/${id}/evidence/${fileId}`),
  downloadEvidence: (id: string, fileId: string) =>
    client.get<Blob>(`${BASE}/instances/${id}/evidence/${fileId}`, {
      responseType: 'blob',
    }),
  patchStepNote: (id: string, executionId: string, data: StepNotePatchRequest) =>
    client.patch<StepExecution>(`${BASE}/instances/${id}/step-executions/${executionId}`, data),
  generateReport: (id: string) =>
    client.get<Blob>(`${BASE}/instances/${id}/pdf`, {
      responseType: 'blob',
    }),
  brak: (id: string, data: BrakCreateRequest) =>
    client.post<BranchResponse>(`${BASE}/instances/${id}/brak`, data),
  getBrakEvents: (id: string) =>
    client.get<BrakEvent[]>(`${BASE}/instances/${id}/brak-events`),
  getBranches: (id: string) =>
    client.get<FlowInstance[]>(`${BASE}/instances/${id}/branches`),
};

/**
 * Production monitoring read-model (epic #271): paged work items and KPI
 * summary. Scope is enforced server-side (own items without VIEW_ALL).
 */
export const productionApi = {
  list: (params?: ProductionListParams, signal?: AbortSignal) =>
    client.get<ProductionPage<ProductionWorkItem>>(`${BASE}/production`, { params, signal }),
  summary: (signal?: AbortSignal) =>
    client.get<ProductionSummary>(`${BASE}/production/summary`, { signal }),
  detail: (id: string, signal?: AbortSignal) =>
    client.get<ProductionDetail>(`${BASE}/production/${id}`, { signal }),
};

export const prostheticsApi = {
  patient: prostheticsPatientApi,
  order: prostheticsOrderApi,
  template: flowTemplateApi,
  instance: flowInstanceApi,
  production: productionApi,
};
