package com.superhumans.audit;

import com.superhumans.audit.AuditActionDefinition.ActionType;
import com.superhumans.audit.AuditActionDefinition.ActorPolicy;
import com.superhumans.audit.AuditActionDefinition.DataClass;
import com.superhumans.audit.AuditActionDefinition.EventClass;
import com.superhumans.audit.AuditActionDefinition.Flag;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;

/** Versioned registry for the atomic audit actions in {@code docs/Audit-Improvement-Plan.md}. */
public final class AuditActionCatalog {

    public static final int CATALOG_VERSION = 1;

    private static final List<AuditActionDefinition> DEFINITIONS = List.of(
            // Platform / common — P01-P18.
            a("platform.auth.session.login", "platform", "session", ActionType.AUTHENTICATE,
                    EventClass.SECURITY, ActorPolicy.USER_OR_INTEGRATION, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.SECURITY, Flag.WRITE),
            a("platform.auth.session.login.failed", "platform", "session", ActionType.AUTHENTICATE,
                    EventClass.SECURITY, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.SECURITY, Flag.WRITE),
            a("platform.auth.session.login.blocked", "platform", "session", ActionType.AUTHENTICATE,
                    EventClass.SECURITY, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.SECURITY, Flag.WRITE),
            a("platform.auth.session.logout", "platform", "session", ActionType.LOGOUT,
                    EventClass.SECURITY, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.SECURITY, Flag.WRITE),
            a("platform.auth.directory.provision", "platform", "directory", ActionType.PROVISION,
                    EventClass.SECURITY, ActorPolicy.SYSTEM, DataClass.PII,
                    false, Flag.MANDATORY, Flag.SECURITY, Flag.WRITE),
            a("platform.auth.token.rejected", "platform", "token", ActionType.ACCESS_DENIED,
                    EventClass.SECURITY, ActorPolicy.UNKNOWN, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.SECURITY, Flag.READ),
            a("platform.user.view", "platform", "users", ActionType.VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.RECOMMENDED, Flag.SECURITY, Flag.READ),
            a("platform.user.role.change", "platform", "users", ActionType.ROLE_CHANGE,
                    EventClass.SECURITY, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.SECURITY, Flag.WRITE),
            a("platform.user.disable", "platform", "users", ActionType.DISABLE,
                    EventClass.SECURITY, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.SECURITY, Flag.WRITE, Flag.DESTRUCTIVE),
            a("platform.rbac.permission.grant", "platform", "rbac", ActionType.PERMISSION_GRANT,
                    EventClass.SECURITY, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.SECURITY, Flag.WRITE),
            a("platform.rbac.permission.revoke", "platform", "rbac", ActionType.PERMISSION_REVOKE,
                    EventClass.SECURITY, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.SECURITY, Flag.WRITE),
            a("platform.audit.search", "platform", "audit", ActionType.SEARCH,
                    EventClass.SECURITY, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.RECOMMENDED, Flag.SECURITY, Flag.READ),
            a("platform.audit.detail.view", "platform", "audit", ActionType.VIEW,
                    EventClass.SECURITY, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.RECOMMENDED, Flag.SECURITY, Flag.READ),
            a("platform.patient.search", "platform", "patient", ActionType.SEARCH,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.MANDATORY, Flag.READ),
            a("platform.patient.record.view", "platform", "patient", ActionType.VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.MANDATORY, Flag.READ),
            a("platform.mis.document.view", "platform", "mis", ActionType.DOCUMENT_VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.MANDATORY, Flag.READ),
            a("platform.mis.catalog.view", "platform", "mis", ActionType.CATALOG_VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.RECOMMENDED, Flag.READ),
            a("platform.bootstrap.seed", "platform", "bootstrap", ActionType.BOOTSTRAP,
                    EventClass.BUSINESS, ActorPolicy.SYSTEM, DataClass.IDENTIFIER,
                    false, Flag.RECOMMENDED, Flag.WRITE, Flag.AUTOMATED),

            // ICU Chart — I01-I42. I30-I35 are atomic create/update actions.
            a("icu.roster.view", "icu", "roster", ActionType.VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.RECOMMENDED, Flag.READ),
            a("icu.episode.record.view", "icu", "episode", ActionType.VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.MANDATORY, Flag.READ),
            a("icu.episode.create", "icu", "episode", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.episode.update", "icu", "episode", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.episode.close", "icu", "episode", ActionType.CLOSE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.episode.archive", "icu", "episode", ActionType.ARCHIVE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE, Flag.DESTRUCTIVE),
            a("icu.clinical_day.create", "icu", "clinical-day", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.clinical_day.update", "icu", "clinical-day", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.clinical_day.sign.nurse", "icu", "clinical-day", ActionType.SIGN,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.clinical_day.sign.doctor", "icu", "clinical-day", ActionType.SIGN,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.clinical_day.close.early", "icu", "clinical-day", ActionType.CLOSE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.clinical_day.reopen", "icu", "clinical-day", ActionType.REOPEN,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.hourly_record.create", "icu", "hourly-record", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.hourly_record.update", "icu", "hourly-record", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.hourly_record.backdate", "icu", "hourly-record", ActionType.BACKDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.medical_order.create", "icu", "medical-order", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.medical_order.update", "icu", "medical-order", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.medical_order.cancel", "icu", "medical-order", ActionType.CANCEL,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.order_execution.plan", "icu", "order-execution", ActionType.PLAN,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.order_execution.plan.finish", "icu", "order-execution", ActionType.PLAN_FINISH,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.order_execution.cancel", "icu", "order-execution", ActionType.CANCEL,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.order_execution.execute", "icu", "order-execution", ActionType.EXECUTE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.order_execution.execute.finish", "icu", "order-execution", ActionType.EXECUTE_FINISH,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.order_execution.backdate", "icu", "order-execution", ActionType.BACKDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.medical_note.create", "icu", "medical-note", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.NARRATIVE,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.medical_note.update", "icu", "medical-note", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.NARRATIVE,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.scale.create", "icu", "scale", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.scale.calculate", "icu", "scale", ActionType.SCORE_CALCULATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.scale.update", "icu", "scale", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.lab_result.create", "icu", "lab-result", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.lab_result.update", "icu", "lab-result", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.patient_state.create", "icu", "patient-state", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.patient_state.update", "icu", "patient-state", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.ventilation.create", "icu", "ventilation", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.ventilation.update", "icu", "ventilation", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.fluid_balance.recalculate", "icu", "fluid-balance", ActionType.RECALCULATE,
                    EventClass.BUSINESS, ActorPolicy.USER_OR_SYSTEM, DataClass.CLINICAL,
                    false, Flag.RECOMMENDED, Flag.WRITE),
            a("icu.pdf.generate", "icu", "pdf", ActionType.GENERATE,
                    EventClass.BUSINESS, ActorPolicy.USER_OR_SYSTEM, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("icu.pdf.download", "icu", "pdf", ActionType.DOWNLOAD,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.READ),
            a("icu.pdf.print.requested", "icu", "pdf", ActionType.PRINT_REQUESTED,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.READ),
            a("icu.clinical_day.auto_close", "icu", "clinical-day", ActionType.AUTO_CLOSE,
                    EventClass.BUSINESS, ActorPolicy.SYSTEM, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE, Flag.AUTOMATED),
            a("icu.clinical_day.escalate", "icu", "clinical-day", ActionType.ESCALATE,
                    EventClass.BUSINESS, ActorPolicy.SYSTEM, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE, Flag.AUTOMATED),
            a("icu.notification.delivery.outcome", "icu", "notification", ActionType.DELIVERY,
                    EventClass.BUSINESS, ActorPolicy.SERVICE, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE, Flag.AUTOMATED),

            // Medication Sheet — D01-D26.
            a("medication.list.view", "medication", "prescription-list", ActionType.VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.READ),
            a("medication.list.create", "medication", "prescription-list", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.list.rename", "medication", "prescription-list", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    true, Flag.MANDATORY, Flag.WRITE),
            a("medication.list.close", "medication", "prescription-list", ActionType.CLOSE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.list.delete", "medication", "prescription-list", ActionType.DELETE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE, Flag.DESTRUCTIVE),
            a("medication.item.add", "medication", "prescription-item", ActionType.ITEM_ADD,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.item.remove", "medication", "prescription-item", ActionType.ITEM_REMOVE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE, Flag.DESTRUCTIVE),
            a("medication.item.day.add", "medication", "prescription-day", ActionType.DAY_ADD,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.item.day.remove", "medication", "prescription-day", ActionType.DAY_REMOVE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE, Flag.DESTRUCTIVE),
            a("medication.dose.plan", "medication", "dose", ActionType.PLAN,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.dose.cancel", "medication", "dose", ActionType.CANCEL,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.dose.replan", "medication", "dose", ActionType.PLAN,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.dose.unassign", "medication", "dose", ActionType.UNASSIGN,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.dose.complete", "medication", "dose", ActionType.COMPLETE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.dose.execute", "medication", "dose", ActionType.DOSE_EXECUTE,
                    EventClass.BUSINESS, ActorPolicy.USER_AND_WITNESS, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.vitals.grid.view", "medication", "vitals", ActionType.VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.READ),
            a("medication.vitals.grid.initialize", "medication", "vitals", ActionType.GRID_INITIALIZE,
                    EventClass.BUSINESS, ActorPolicy.USER_OR_SYSTEM, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.vitals.entry.create", "medication", "vitals", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.vitals.entry.update", "medication", "vitals", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.interactions.import", "medication", "interactions", ActionType.IMPORT,
                    EventClass.SECURITY, ActorPolicy.USER_OR_SERVICE, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.SECURITY, Flag.WRITE),
            a("medication.interactions.catalog.view", "medication", "interactions", ActionType.CATALOG_VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.RECOMMENDED, Flag.READ),
            a("medication.interactions.warning.view", "medication", "interactions", ActionType.WARNING_VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.CLINICAL,
                    false, Flag.RECOMMENDED, Flag.READ),
            a("medication.pdf.info", "medication", "pdf", ActionType.PDF_INFO,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.RECOMMENDED, Flag.READ),
            a("medication.pdf.generate", "medication", "pdf", ActionType.GENERATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("medication.pdf.download", "medication", "pdf", ActionType.DOWNLOAD,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.READ),
            a("medication.pdf.print.requested", "medication", "pdf", ActionType.PRINT_REQUESTED,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.READ),

            // Prosthetics Manufacturing — R01-R31.
            a("prosthetics.candidate.search", "prosthetics", "candidate", ActionType.SEARCH,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.MANDATORY, Flag.READ),
            a("prosthetics.patient.record.view", "prosthetics", "patient", ActionType.VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.MANDATORY, Flag.READ),
            a("prosthetics.order.document.view", "prosthetics", "order-document", ActionType.DOCUMENT_VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.MANDATORY, Flag.READ),
            a("prosthetics.order.provision", "prosthetics", "order", ActionType.ORDER_PROVISION,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.PII,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.template.create.version", "prosthetics", "template", ActionType.CREATE_VERSION,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.template.update", "prosthetics", "template", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.template.archive", "prosthetics", "template", ActionType.ARCHIVE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE, Flag.DESTRUCTIVE),
            a("prosthetics.instance.create", "prosthetics", "instance", ActionType.CREATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.PII,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.instance.view", "prosthetics", "instance", ActionType.VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.RECOMMENDED, Flag.READ),
            a("prosthetics.instance.snapshot.view", "prosthetics", "instance", ActionType.SNAPSHOT_VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.READ),
            a("prosthetics.instance.start", "prosthetics", "instance", ActionType.START,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.step.complete", "prosthetics", "step", ActionType.STEP_COMPLETE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.resource.record", "prosthetics", "resource", ActionType.RESOURCE_RECORD,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.step.note.update", "prosthetics", "step", ActionType.UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.NARRATIVE,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.instance.backward", "prosthetics", "instance", ActionType.BACKWARD,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.instance.pause", "prosthetics", "instance", ActionType.PAUSE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.instance.resume", "prosthetics", "instance", ActionType.RESUME,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.instance.fail", "prosthetics", "instance", ActionType.FAIL,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.NARRATIVE,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.brak.confirm", "prosthetics", "brak", ActionType.BRAK_CONFIRM,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.NARRATIVE,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.brak.branch", "prosthetics", "brak", ActionType.BRANCH,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.notification.queue", "prosthetics", "notification", ActionType.QUEUE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.evidence.upload", "prosthetics", "evidence", ActionType.UPLOAD,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.evidence.list.view", "prosthetics", "evidence", ActionType.LIST_VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.RECOMMENDED, Flag.READ),
            a("prosthetics.evidence.download", "prosthetics", "evidence", ActionType.DOWNLOAD,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.READ),
            a("prosthetics.evidence.delete", "prosthetics", "evidence", ActionType.DELETE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE, Flag.DESTRUCTIVE),
            a("prosthetics.report.generate", "prosthetics", "report", ActionType.GENERATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.WRITE),
            a("prosthetics.report.download", "prosthetics", "report", ActionType.DOWNLOAD,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.READ),
            a("prosthetics.report.print.requested", "prosthetics", "report", ActionType.PRINT_REQUESTED,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.RESTRICTED,
                    false, Flag.MANDATORY, Flag.READ),
            a("prosthetics.production.worklist.view", "prosthetics", "production", ActionType.WORKLIST_VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.RECOMMENDED, Flag.READ),
            a("prosthetics.production.detail.view", "prosthetics", "production", ActionType.DETAIL_VIEW,
                    EventClass.USER_ACTIVITY, ActorPolicy.USER, DataClass.PII,
                    false, Flag.MANDATORY, Flag.READ),
            a("prosthetics.production.normative.update", "prosthetics", "production", ActionType.CONFIG_UPDATE,
                    EventClass.BUSINESS, ActorPolicy.USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE, Flag.SECURITY),
            a("prosthetics.notification.delivery.outcome", "prosthetics", "notification", ActionType.DELIVERY,
                    EventClass.BUSINESS, ActorPolicy.SERVICE_INITIATED_BY_USER, DataClass.IDENTIFIER,
                    false, Flag.MANDATORY, Flag.WRITE, Flag.AUTOMATED));

    private static final Map<String, AuditActionDefinition> BY_CODE = DEFINITIONS.stream()
            .collect(Collectors.toUnmodifiableMap(AuditActionDefinition::code, Function.identity()));

    private AuditActionCatalog() {
    }

    public static List<AuditActionDefinition> definitions() {
        return DEFINITIONS;
    }

    public static Map<String, AuditActionDefinition> byCode() {
        return BY_CODE;
    }

    public static AuditActionDefinition require(String code) {
        AuditActionDefinition definition = BY_CODE.get(code);
        if (definition == null) {
            throw new IllegalArgumentException("Unknown audit action: " + code);
        }
        return definition;
    }

    public static List<AuditActionDefinition> forModule(String module) {
        return DEFINITIONS.stream().filter(definition -> definition.module().equals(module)).toList();
    }

    private static AuditActionDefinition a(
            String code,
            String module,
            String area,
            ActionType type,
            EventClass eventClass,
            ActorPolicy actor,
            DataClass dataClass,
            boolean conditional,
            Flag... flags) {
        return new AuditActionDefinition(code, module, area, type, eventClass, actor, dataClass,
                Set.of(flags), conditional);
    }
}
