--liquibase formatted sql

--changeset phase-3:1
--comment Migration: SH_Users to users table.
-- If SH_Users table exists in legacy DB, run this to convert rows to the ICU users table.
-- INT PK (SH_UserId) → UUID PK (randomly generated, stored mapping not needed for MVP).
-- Role mapping:
--   SH_Users.user_role='ADMIN', business_role='ADMIN' → UserRole.ADMINISTRATOR
--   SH_Users.user_role='EMPLOYEE', business_role='DOCTOR' → UserRole.DOCTOR
--   SH_Users.user_role='EMPLOYEE', business_role='NURSE' → UserRole.NURSE
--   SH_Users.user_role='USER' → skipped (no corresponding ICU role)

-- INSERT INTO users (id, login, password_hash, full_name, role, email, created_at, created_by, updated_at, updated_by, version)
-- SELECT
--     gen_random_uuid(),
--     u.login,
--     u.password,
--     CONCAT(u.firstName, ' ', u.lastName),
--     CASE
--         WHEN u.user_role = 'ADMIN' THEN 'ADMINISTRATOR'
--         WHEN u.user_role = 'EMPLOYEE' AND u.business_role = 'DOCTOR' THEN 'DOCTOR'
--         WHEN u.user_role = 'EMPLOYEE' AND u.business_role = 'NURSE' THEN 'NURSE'
--         ELSE NULL
--     END,
--     u.email,
--     NOW(), 0, NOW(), 0, 0
-- FROM SH_Users u
-- WHERE u.login NOT IN (SELECT login FROM users)
--   AND CASE
--         WHEN u.user_role = 'ADMIN' THEN 'ADMINISTRATOR'
--         WHEN u.user_role = 'EMPLOYEE' AND u.business_role = 'DOCTOR' THEN 'DOCTOR'
--         WHEN u.user_role = 'EMPLOYEE' AND u.business_role = 'NURSE' THEN 'NURSE'
--         ELSE NULL
--     END IS NOT NULL;

--rollback DELETE FROM users WHERE created_by = 0 AND version = 0;
